### PR TITLE
autogen: add check for YAKSA_AUTOGEN_PUP_NESTING

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

This allows CI jobs to easily control nested pup levels. The direct
autogen argument can't be used without changing the default for embedded
builds such as mpich.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Have read and agree to the Yaksa CLA terms (https://github.com/pmodels/yaksa/wiki/Yaksa-Contributor-License-Agreement)

### CODE REVIEW

**Comment by pavanbalaji** [comment]
@hzhou  This PR never got merged in.  Is this still relevant?

**Comment by hzhou** [comment]
> 
> 
> @hzhou This PR never got merged in. Is this still relevant?

It is still needed if we wish to control the `--pup-max-nesting` during a MPICH CI testing. I think it is useful to expedite some jenkins job.

**Comment by pavanbalaji** [comment]
> > @hzhou This PR never got merged in. Is this still relevant?
> 
> It is still needed if we wish to control the `--pup-max-nesting` during a MPICH CI testing. I think it is useful to expedite some jenkins job.

@hzhou  OK, can you rebase it to main?  The system will automatically rerun the tests.

**Review by pavanbalaji — APPROVED** [review]

**Comment by pavanbalaji** [comment]
@hzhou   I've approved this, but it needs to be rebased on to main before merging.

**Pull request merged**
