### PR TITLE
Generalize assignment code

### PR DESCRIPTION
**Pull request by pavanbalaji**
## Pull Request Description

Attempt to generalize the assignment code inside pack/unpack to allow for cases where the displacement of buffers passed by users does not directly align to the basic type size.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Have read and agree to the Yaksa CLA terms (https://github.com/pmodels/yaksa/wiki/Yaksa-Contributor-License-Agreement)

### CODE REVIEW

**Comment by pavanbalaji** [comment]
This PR is not fully ready yet.  The code is written in a way to try to minimize performance impact, but the actual impact is not fully analyzed yet.

**Comment by pavanbalaji** [comment]
There are three types of packing kernels that need to be considered:

1. Array-style assignments.  This is the original version of the code in yaksa.  It essentially looks like a multiple level for loop followed by an array assignment from the source buffer to the destination buffer.  This format is the easiest for the compiler to optimize because it implicitly knows that the data is correctly aligned to the correct datatype.  Also, arrays are easier for the compiler to vectorize.  This version assumes that (1) all buffers are correctly aligned and that (2) the buffers are essentially arrays of the basic type -- so the displacements have to be multiple of the type size.

2. Pointer-offset style assignment.  This is the version of the code created by this PR currently.  The generated assembly code right now seems to be identical to the array-format assignment, so we might not lose performance.  But it'll likely conflict with @shintaro-iwasaki's work on vectorization and would likely hurt performance when vectorization is enabled, at least if the compiler cannot analyze the code to convert it to an array format.  This version retains the first assumption above, but drops the second assumption.

3. Fully-generic types.  This version assumes no alignment.  So we cannot perform a direct assignment of types.  We'd need to convert the code to either use memcpy or a loop of assignments for byte-sized elements.  This version would likely lose a lot more performance.

**Comment by pavanbalaji** [comment]
Based on initial evaluation, the loss of vectorization is unclear with this PR.  We obviously need to investigate it further, but for now, this PR should be OK.

This still does not support completely arbitrary (no alignment) datatypes.  But it is hard to see whether that is needed.

**Review by shintaro-iwasaki — APPROVED** [review]
> Based on initial evaluation, the loss of vectorization is unclear with this PR. We obviously need to investigate it further, but for now, this PR should be OK.

Yes I agree. I approved this PR. If it passes all the tests, it should be good to merge.

**Comment by pavanbalaji** [comment]
Checking on CUDA systems too, to confirm before merging.

**Comment by pavanbalaji** [comment]
Unclear why the configs test failed.  Retrying.

test:yaksa/review/configs

**Comment by pavanbalaji** [comment]
test:yaksa/review

**Pull request merged**
