### PR TITLE
backend/glue: skip over buffer attr query if already done

### PR DESCRIPTION
**Pull request by pavanbalaji**
## Pull Request Description

backend/glue: skip over buffer attr query if already done

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Have read and agree to the Yaksa CLA terms (https://github.com/pmodels/yaksa/wiki/Yaksa-Contributor-License-Agreement)

### CODE REVIEW

**Review by yfguo — APPROVED** [review]

**Comment by pavanbalaji** [comment]
test:yaksa/review

**Comment by pavanbalaji** [comment]
test:yaksa/review/sanitizer

**Comment by pavanbalaji** [comment]
test:yaksa/review/warnings
test:yaksa/review/configs
test:yaksa/review/platforms

**Comment by pavanbalaji** [comment]
test:yaksa/review/warnings

**Comment by pavanbalaji** [comment]
test:yaksa/warnings

**Pull request merged**
