### PR TITLE
build: add per dir test target

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Add sub test targets to allow optional quick testing, for example, `make test-simple`.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Have read and agree to the Yaksa CLA terms (https://github.com/pmodels/yaksa/wiki/Yaksa-Contributor-License-Agreement)

### CODE REVIEW

**Comment by hzhou** [comment]
test: yaksa/quick

**Comment by pavanbalaji** [comment]
This PR needs to be updated based on changes from #26

**Comment by hzhou** [comment]
test:yaksa/quick

**Comment by hzhou** [comment]
@pavanbalaji Updated.

**Comment by hzhou** [comment]
test:yaksa

**Pull request merged**
