### PR TITLE
Add yaksa_pack_stream and yaksa_unpack_stream

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Add `yaksa_pack_stream` and `yaksa_unpack_stream`.

The explicit stream version of routines will only enqueue memory operations and host routines (as stream callbacks).

image

In an optimal case, where the yaksa operation is just a single kernel, we just enqueue that kernel(s). But there are fallback cases that we need enqueue CPU callbacks. For example, we may need run pre/post CPU operations.

## Notes

* The progress routines are rather messy -- duplicating ~1,600 loc. I am focusing on getting the code work, and will leave the refactoring to the future.
* The user-supplied stream has to match the yaksa internal device -- the target device.
* Cuda runtime defines the semantics of stream and stream callback. It is difficult to make an abstraction that works with all potential gpu driver, thus --
    - use `void *` for `stream`. For cuda, that is `cudaStream_t *` -- note this is one additional pointer indirection.  Internally, `cudaStream_t` is already a pointer. We can't directly use `cudaStream_t` because it could be an integer or a `struct`. *bad*: this prevents us to effectively differentiate different streams.
    - use `void (*fn)(void *data)` for host callback function prototype. -- if this is not compatible with other GPU drivers, the backend needs to employ wrapper functions.
* Ideally, we would hope there to be some standardization. For example, define `stream` to be an `integer` and host callbacks be `void (*fn)(void *data)` . Ultimately, I belive at some point an open standardization gonna come along, like `OpenGL`.
* The error recovery is fragile. Since we are queuing up the operations, how would we deal with *unexpected* errors?

## TODO
* [x] Add tests

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Have read and agree to the Yaksa CLA terms (https://github.com/pmodels/yaksa/wiki/Yaksa-Contributor-License-Agreement)

### CODE REVIEW

**Comment by hzhou** [comment]
@yfguo FYI. Still WIP.

**Comment by hzhou** [comment]
test:yaksa/gpu

**Comment by hzhou** [comment]
test:yaksa/gpu

**Comment by hzhou** [comment]
test:yaksa/gpu

**Review by yfguo — APPROVED** [review]

**Comment by hzhou** [comment]
test:yaksa/gpu

**Comment by hzhou** [comment]
test:yaksa/gpu

**Comment by hzhou** [comment]
test:yaksa/gpu

**Comment by hzhou** [comment]
test:yaksa/gpu

**Comment by hzhou** [comment]
test:yaksa/gpu

**Comment by hzhou** [comment]
@yfguo Could you review the last 6 commits, which are new since your last review? I'll squash all the progress commits after the review.

**Review by yfguo — APPROVED** [review]

**Pull request merged**
