### PR TITLE
backend: fix fast-path conditions for reduce operations

### PR DESCRIPTION
**Pull request by minsii**
## Pull Request Description

This PR contains two major changes:
1.  Add p2p-enabled case for the fast-path of **REPLACE** operation

2. [c346933b](https://github.com/pmodels/yaksa/commit/c346933b5262809b433c322a2552dd1c06f2e683) missed the fast-path check for non-REPLACE reduce operations. Now we add it back. Below are the fast-path conditions for **non-REPLACE** operations:
    - d2d pack/unpack: same device and buffer is aligned
    - d2m or m2d pack/unpack: same device or device-host, and with aligned buffer

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Have read and agree to the Yaksa CLA terms (https://github.com/pmodels/yaksa/wiki/Yaksa-Contributor-License-Agreement)

### CODE REVIEW

**Comment by minsii** [comment]
Locally tested that a reduce operation can go through fast-path now, if conditions are met. Tested for both device-to-device and device-to-managed.

**Review by zhenggb72 — APPROVED** [review]
Looks good to me. I assume the fast path for reduction is a separate PR which comes later.

**Comment by minsii** [comment]
In this PR, eacfd5adb54877f3e44e3eb7ad3ecd94b6325241 should add back the fast-path for non-REPLACE reduction. Can you please check if I miss anything?

**Comment by minsii** [comment]
Pushed to rebase against main.

**Comment by zhenggb72** [comment]
> In this PR, [eacfd5a](https://github.com/pmodels/yaksa/commit/eacfd5adb54877f3e44e3eb7ad3ecd94b6325241) should add back the fast-path for non-REPLACE reduction. Can you please check if I miss anything? @zhenggb72


You are right, ignore my previous comment about that. This PR is good to go.

**Comment by minsii** [comment]
@hzhou Gengbing has approved it. But it looks like we still need one approval from pmodels core. Would you mind reviewing it for me? It fixes&improves the fastpath pack/unpack.

**Review by hzhou — APPROVED** [review]
LGTM.

**Pull request merged**
