### PR TITLE
runtests: some enhancement

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

* add verbose options for runtests.py, so we can see more what's going on.
* check whether we are being redirected and disable color escape output.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Have read and agree to the Yaksa CLA terms (https://github.com/pmodels/yaksa/wiki/Yaksa-Contributor-License-Agreement)

### CODE REVIEW

**Comment by hzhou** [comment]
test: yaksa/quick

**Comment by hzhou** [comment]
test:yaksa/quick

**Comment by hzhou** [comment]
test:yaksa/quick

**Comment by hzhou** [comment]
test:yaksa
test:yaksa/quick

**Comment by hzhou** [comment]
> This needs to be split into three different PRs: (1) the runtests improvements, (2) the per-directory test target, and (3) the integration of dtpools into the top-level makefile.

dtpools commit split to PR #26.

@pavanbalaji Would you like me to split the rest of the two PRs now? Or I can close this PR and reopen it whenever we like.

**Comment by pavanbalaji** [comment]
> > This needs to be split into three different PRs: (1) the runtests improvements, (2) the per-directory test target, and (3) the integration of dtpools into the top-level makefile.
> 
> dtpools commit split to PR #26.
> 
> @pavanbalaji Would you like me to split the rest of the two PRs now? Or I can close this PR and reopen it whenever we like.

It'll be good to not lose the other pieces, and create PRs for them too.

**Comment by hzhou** [comment]
test: yaksa/quick

**Comment by hzhou** [comment]
test: yaksa

**Pull request merged**
