### PR TITLE
backend: fix threading bug

### PR DESCRIPTION
**Pull request by pavanbalaji**
## Pull Request Description

Once the request is enqueued into the progress engine, the GPU driver
cannot be updated anymore.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Have read and agree to the Yaksa CLA terms (https://github.com/pmodels/yaksa/wiki/Yaksa-Contributor-License-Agreement)

### CODE REVIEW

**Review by yfguo — APPROVED** [review]
The change looks good to me. Can you push it again and retrigger the test? I am not sure why the test was failing on this one.

**Comment by pavanbalaji** [comment]
> Can you push it again and retrigger the test? I am not sure why the test was failing on this one.

The failed test is because of a jenkins setup issue that systems is currently working on.  I'll retrigger the test once it's fixed.

**Comment by pavanbalaji** [comment]
test:review/platforms

**Comment by pavanbalaji** [comment]
test:yaksa/review/platforms

**Pull request merged**
