### PR TITLE
backend/ze: simplify the use of immediate command list

### PR DESCRIPTION
**Pull request by zhenggb72**
Append task consecutively to an immediate cmd list without having to
wait for the previous tasks to finish

Signed-off-by: Gengbin Zheng <gengbin.zheng@intel.com>

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Have read and agree to the Yaksa CLA terms (https://github.com/pmodels/yaksa/wiki/Yaksa-Contributor-License-Agreement)

### CODE REVIEW

**Comment by zhenggb72** [comment]
test:yaksa/gpu

**Comment by zhenggb72** [comment]
test:yaksa/gpu

**Review by yfguo — APPROVED** [review]
LGTM

**Comment by yfguo** [comment]
Just retrigger the warning test.

**Pull request merged**
