### PR TITLE
m4: Add -Wpedantic to strict flags

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

Add -Wpedantic to catch violations of ISO C, such as returning a value
from a void function that have slipped into the code in the past.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Commits are self-contained and do not do two things at once
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Have read and agree to the Yaksa CLA terms (https://github.com/pmodels/yaksa/wiki/Yaksa-Contributor-License-Agreement)

### CODE REVIEW

**Comment by raffenet** [comment]
Reverted #146 to confirm the new strict warnings check will catch the problematic code.

**Comment by raffenet** [comment]
Void return warning was correctly showed with this PR. https://jenkins-pmrs.cels.anl.gov/job/yaksa-warnings/181/

Problem: the addition of this flag causes a number of warnings because of the inclusion of `cuda.h` (anonymous struct/union, invalid enumerator value).

**Comment by raffenet** [comment]
> Problem: the addition of this flag causes a number of warnings because of the inclusion of `cuda.h` (anonymous struct/union, invalid enumerator value).

We can raise the C standard level to `c11` for CUDA builds to silence the anonymous struct/union warnings. The enum value may need to be fixed in `cuda.h`, though.

**Comment by pavanbalaji** [comment]
> > Problem: the addition of this flag causes a number of warnings because of the inclusion of `cuda.h` (anonymous struct/union, invalid enumerator value).
> 
> We can raise the C standard level to `c11` for CUDA builds to silence the anonymous struct/union warnings. The enum value may need to be fixed in `cuda.h`, though.

I think adding `-Wpedantic` is more problematic than helpful.  I'd recommend simply dropping it.

**Comment by pavanbalaji** [comment]
@raffenet   What's the plan for this?  Should this be closed?

**Comment by raffenet** [comment]
I agree we should just drop it.

**Pull request closed without merging**
