### PR TITLE
test: update runtests.py

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description

Update `test/runtests.py` with following changes:

* load all tests into tests as list
* store each test results into the test dict
* support specical directives: prefix, condition, testlist, and echo
* support multiple testlist files on the command line

Note: this is a split and prereqisite for PR #10.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [ ] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Have read and agree to the Yaksa CLA terms (https://github.com/pmodels/yaksa/wiki/Yaksa-Contributor-License-Agreement)

### CODE REVIEW

**Comment by hzhou** [comment]
test: yaksa

**Comment by hzhou** [comment]
@pavanbalaji This is my attempt of the split. The main goal is to let runtests.py pre-load all tests into a testlist, so it can be flexible in whether we want to do it recusively or integrally. But once we let go of the recursive nature, some of the directives in the testlist become necessary.

**Comment by pavanbalaji** [comment]
@hzhou This is the part that I mentioned was orthogonal to the core change.  Can you do the core fix first?  We can discuss this part later, because it includes many things that are just personal preferences and are different from person to person.

**Comment by hzhou** [comment]
If we let go of the recursive make structure, then we have to load all testlists together, right? For example, we can't simply descend down the directory and do sub-make.

**Comment by pavanbalaji** [comment]
> If we let go of the recursive make structure, then we have to load all testlists together, right? For example, we can't simply descend down the directory and do sub-make.

This PR does more than remove the recursive make structure.  Can you split out that part?

**Comment by hzhou** [comment]
> This PR does more than remove the recursive make structure. Can you split out that part?

This PR still reserves the recursive make structure.

**Comment by pavanbalaji** [comment]
> > This PR does more than remove the recursive make structure. Can you split out that part?
> 
> This PR still reserves the recursive make structure.

This PR does more things that I'm comfortable signing off right now.  That's the reason I'm asking you to separate out things that you consider cleanup, from things that are needed to fix the dependency issue.

**Pull request closed without merging**
