### PR TITLE
backend: Use correct device for peer access check

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

With the change to lazily init CUDA resources, a crash occurs in MPICH when doing certain device-to-device transfers. The underlying issue is when using a mapped device (supplied via info) for transfers, we need to use the mapped device in the p2p check. Otherwise peer access might not be initialized, resulting in illegal memory access.

## Expected Impact

Fix CUDA support in MPICH with yaksa lazy init.

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Add comments such that someone without knowledge of the code could understand
* [x] Have read and agree to the Yaksa CLA terms (https://github.com/pmodels/yaksa/wiki/Yaksa-Contributor-License-Agreement)

### CODE REVIEW

**Comment by raffenet** [comment]
test:yaksa/gpu

**Comment by raffenet** [comment]
test:yaksa/gpu

**Comment by raffenet** [comment]
test:yaksa/gpu

**Comment by raffenet** [comment]
test:yaksa/gpu

**Comment by raffenet** [comment]
test:yaksa/gpu

**Comment by raffenet** [comment]
test:yaksa/gpu

**Comment by raffenet** [comment]
test:yaksa/gpu

**Comment by raffenet** [comment]
test:yaksa/gpu

**Comment by raffenet** [comment]
test:yaksa/gpu

**Review by hzhou — APPROVED** [review]
Looks good! It's nice cleanup (and fix).

**Pull request merged**
